import json
# from Board import *
# from Models import * 
from MultiplayerModels import *

# Data to be written to the JSON file
a = []
i = 0
while i < 9:
    a.append(1)
    i+=1
i = 0
while i<4:
    a.append(2)
    i+= 1
i = 0
while i < 9:
    a.append(3)
    i+=1

# saveMap = []

# map = []
# map.append(Wall("Pictures/Tiles/Wall.png", 0, 11))
# map.append(Wall("Pictures/Tiles/Wall.png", 0, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 0, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 1, 11))
# map.append(ControlledArea("Pictures/Tiles/SM_entry.png", "Pictures/Tiles/Floor_burning.png", 1, 12, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 1, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 2, 11))
# map.append(ControlledArea("Pictures/Tiles/SM_entry.png", "Pictures/Tiles/Floor_burning.png", 2, 12, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 2, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 3, 11))
# map.append(ControlledArea("Pictures/Tiles/SM_entry.png", "Pictures/Tiles/Floor_burning.png", 3, 12, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 3, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 4, 11))
# map.append(ControlledArea("Pictures/Tiles/SM_entry.png", "Pictures/Tiles/Floor_burning.png", 4, 12, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 4, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 5, 11))
# map.append(ControlledArea("Pictures/Tiles/SM_entry.png", "Pictures/Tiles/Floor_burning.png", 5, 12, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 5, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 11))
# map.append(Door("Pictures/Tiles/Door_open_V.png", "Pictures/Tiles/Door_V.png", "Pictures/Tiles/Door_burning_V.png", 6, 12, 1, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 7, 11, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 7, 12, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 7, 13, 1))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 8, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 11, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 12, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 13, 1))
# map.append(Door("Pictures/Tiles/Door_open_H.png", "Pictures/Tiles/Door_H.png", "Pictures/Tiles/Door_burning_H.png", 8, 14, 1, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 9, 11, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 9, 12, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 9, 13, 1))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 11))
# map.append(Door("Pictures/Tiles/Door_open_V.png", "Pictures/Tiles/Door_V.png", "Pictures/Tiles/Door_burning_V.png", 10, 12, 1, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 15, 2))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 15))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 16))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 16, 2))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 16))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 17))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 17, 2))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 17))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 18))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 18, 2))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 18))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 19))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 19))
# map.append(Door("Pictures/Tiles/Door_open_H.png", "Pictures/Tiles/Door_H.png", "Pictures/Tiles/Door_burning_H.png", 8, 19, 3, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 19))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 19))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 20))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 7, 20, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 20, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 9, 20, 3))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 20))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 21))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 7, 21, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 21, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 9, 21, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 10, 21, 3))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 22))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 7, 22, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 8, 22, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 9, 22, 3))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 22))
# map.append(Wall("Pictures/Tiles/Wall.png", 6, 23))
# map.append(Wall("Pictures/Tiles/Wall.png", 7, 23))
# map.append(Wall("Pictures/Tiles/Wall.png", 8, 23))
# map.append(Wall("Pictures/Tiles/Wall.png", 9, 23))
# map.append(Wall("Pictures/Tiles/Wall.png", 10, 23))
# map.append(Wall("Pictures/Tiles/Wall.png", 11, 20))
# map.append(Door("Pictures/Tiles/Door_open_V.png", "Pictures/Tiles/Door_V.png", "Pictures/Tiles/Door_burning_V.png", 11, 21, 4, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 11, 22))
# map.append(EntryPoint("Pictures/Tiles/lurking.png", 12, 19, (0,1)))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 12, 20, 4))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 12, 21, 4))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 12, 22, 4))
# map.append(EntryPoint("Pictures/Tiles/lurking.png", 12, 23, (0, -1)))
# map.append(Wall("Pictures/Tiles/Wall.png", 13, 20))
# map.append(Wall("Pictures/Tiles/Wall.png", 13, 21))
# map.append(Wall("Pictures/Tiles/Wall.png", 13, 22))
# map.append(Wall("Pictures/Tiles/Wall.png", 11, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 11, 12, 5))
# map.append(Wall("Pictures/Tiles/Wall.png", 11, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 12, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 12, 12, 5))
# map.append(Wall("Pictures/Tiles/Wall.png", 12, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 13, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 13, 12, 5))
# map.append(Wall("Pictures/Tiles/Wall.png", 13, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 14, 11))
# map.append(Wall("Pictures/Tiles/Wall.png", 14, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 14, 9))
# map.append(Wall("Pictures/Tiles/Wall.png", 14, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 14, 12, 6))
# map.append(Wall("Pictures/Tiles/Wall.png", 14, 13))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 15, 12, 6))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 16, 12, 6))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 15, 11, 6))
# map.append(Wall("Pictures/Tiles/Wall.png", 15, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 15, 8))
# map.append(Wall("Pictures/Tiles/Wall.png", 16, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 16, 11))
# map.append(Wall("Pictures/Tiles/Wall.png", 16, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 15, 10, 7))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 15, 9, 7))
# map.append(Door("Pictures/Tiles/Door_open_V.png", "Pictures/Tiles/Door_V.png", "Pictures/Tiles/Door_burning_V.png", 16, 9, 7, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 16, 8))
# map.append(Wall("Pictures/Tiles/Wall.png", 17, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 17, 12, 8))
# map.append(Wall("Pictures/Tiles/Wall.png", 17, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 18, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 18, 12, 8))
# map.append(Wall("Pictures/Tiles/Wall.png", 18, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 19, 12, 8))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 17, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 17, 9, 9))
# map.append(Wall("Pictures/Tiles/Wall.png", 17, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 18, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 18, 9, 9))
# map.append(Wall("Pictures/Tiles/Wall.png", 18, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 19, 9, 9))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 8, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 20, 9, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 9, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 22, 9, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 10, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 11, 11))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 20, 12, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 12, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 22, 12, 11))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 13))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 13, 11))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 14))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 14, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 15, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 15))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 16))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 16, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 16))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 17))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 17, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 17))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 18))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 18, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 18))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 19))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 19, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 19))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 20, 20, 13))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 20, 13))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 22, 20, 13))
# map.append(EntryPoint("Pictures/Tiles/lurking.png", 19, 20, (1, 0)))
# map.append(EntryPoint("Pictures/Tiles/lurking.png", 23, 20, (-1, 0)))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 21))
# map.append(Wall("Pictures/Tiles/Wall.png", 21, 21))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 21))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 7))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 7, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 7))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 6))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 6, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 6))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 5))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 5, 14))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 5))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 4))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 4))
# map.append(Door("Pictures/Tiles/Door_open_H.png", "Pictures/Tiles/Door_H.png", "Pictures/Tiles/Door_burning_H.png", 21, 4, 15, False))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 4))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 4))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 3))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 20, 3, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 3, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 22, 3, 15))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 3))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 2))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 20, 2, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 2, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 22, 2, 15))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 2))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 1))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 20, 1, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 21, 1, 15))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 22, 1, 15))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 1))
# map.append(Wall("Pictures/Tiles/Wall.png", 19, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 20, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 21, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 22, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 0))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 23, 9, 16))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 24, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 24, 9, 16))
# map.append(Wall("Pictures/Tiles/Wall.png", 24, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 25, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 25, 9, 16))
# map.append(Wall("Pictures/Tiles/Wall.png", 25, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 23, 12, 17))
# map.append(Wall("Pictures/Tiles/Wall.png", 23, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 24, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 24, 12, 17))
# map.append(Wall("Pictures/Tiles/Wall.png", 24, 13))
# map.append(Wall("Pictures/Tiles/Wall.png", 25, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 25, 12, 17))
# map.append(Wall("Pictures/Tiles/Wall.png", 25, 13))
# map.append(EntryPoint("Pictures/Tiles/lurking.png", 27, 7, (0,1)))
# map.append(Wall("Pictures/Tiles/Wall.png", 26, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 27, 8, 18))
# map.append(Wall("Pictures/Tiles/Wall.png", 28, 8))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 26, 9, 18))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 27, 9, 18))
# map.append(Wall("Pictures/Tiles/Wall.png", 28, 9))
# map.append(Wall("Pictures/Tiles/Wall.png", 26, 10))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 27, 10, 18))
# map.append(Wall("Pictures/Tiles/Wall.png", 28, 10))
# map.append(Wall("Pictures/Tiles/Wall.png", 26, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 27, 11, 19))
# map.append(Wall("Pictures/Tiles/Wall.png", 28, 11))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 26, 12, 19))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 27, 12, 19))
# map.append(Wall("Pictures/Tiles/Wall.png", 28, 12))
# map.append(Wall("Pictures/Tiles/Wall.png", 26, 13))
# map.append(Tile("Pictures/Tiles/Floor_1.png", "Pictures/Tiles/Floor_burning.png", 27, 13, 19))
# map.append(Wall("Pictures/Tiles/Wall.png", 28, 13))
# map.append(EntryPoint("Pictures/Tiles/lurking.png", 27, 14, (0,-1)))

# for tile in map:
#     if isinstance(tile, Door):
#         saveMap.append(((tile.x, tile.y), "door", tile.picturePath, tile.sector, tile.pictureClosedPath, tile.isOpen, tile.burningPictureFilePath))
#     elif isinstance(tile, Wall):
#         saveMap.append(((tile.x, tile.y), "wall", tile.picturePath))
#     elif isinstance(tile, EntryPoint):
#         saveMap.append(((tile.x, tile.y), "entry", tile.picturePath, tile.face))
#     elif isinstance(tile, ControlledArea):
#         saveMap.append(((tile.x, tile.y), "control", tile.picturePath, tile.sector, tile.burningPictureFilePath))
#     elif isinstance(tile, Tile):
#         saveMap.append(((tile.x, tile.y), "tile", tile.picturePath, tile.sector, tile.burningPictureFilePath))

# smModelList = []
# smModelSaveList = []
# smModelList.append(SpaceMarine("Powersword", "sergant", "Pictures/Models/Brother.png"))
# smModelList.append(SpaceMarine("Flamer", "brother", "Pictures/Models/Brother.png"))
# smModelList.append(SpaceMarine("Bolter", "brother", "Pictures/Models/Brother.png"))
# smModelList.append(SpaceMarine("Bolter", "brother", "Pictures/Models/Brother.png"))
# smModelList.append(SpaceMarine("Bolter", "brother", "Pictures/Models/Brother.png"))

# for model in smModelList:
#     smModelSaveList.append((model.weapon, model.rank, model.pictureFilePath))

smlist = [SpaceMarine("powersword","sergant"), SpaceMarine("flamer","brother"), SpaceMarine("bolter","brother"), SpaceMarine("bolter","brother"), SpaceMarine("bolter","brother")]
smsavelist = []
for model in smlist:
    smsavelist.append(model.to_dict())

data = {
    "level": 1,
    "blipList" : a,
    #"map" : saveMap,
    "startBlip": 2,
    "reinforcement" : 2,
    "smModelList" : smsavelist,
    "broodLord": False
}

# File path to save the JSON file
file_path = "Levels/level_1.json"

# Writing data to the JSON file
with open(file_path, 'w') as json_file:
    json.dump(data, json_file, indent=4)

with open(file_path, 'r') as json_file:
    data = json.load(json_file)

# Printing loaded data
print(data)