@startuml Game
class MultiplayerClassClient {
  GameRole role
  list players_in_lobby
  bool is_host
  pygame.display screen
  Game_State state
  bool running
  int level
  list smlist

  void main() 
  void connect()
}

enum GameRole{
  SPECTATOR = "spectator"
  SPACEMARINE = "spacemarine"
  GENSTEALER = "genstealer"
}

enum Game_State{
  MAINMENU = "main"
  LOBBY = "lobby"
  CONFIG = "config"
  SETUP = "setup"
}
class Server {
}

MultiplayerClassClient "*" <-- "1" Server
@enduml